############################
# STEP 1 build executable binary
############################
FROM golang:alpine AS builder

WORKDIR /app

COPY main.go .

# Build the binary.
RUN go build -o /go/bin/main

############################
# STEP 2 build a small image
############################
FROM alpine:3.7

# Copy our static executable.
COPY --from=builder /go/bin/main /go/bin/main

# Run the hello binary.
ENTRYPOINT ["/go/bin/main"]
