apiVersion: apps/v1
kind: Deployment
metadata:
  name: complex-app
spec:
  selector:
    matchLabels:
      app: complex
  replicas: 1
  template:
    metadata:
      labels:
        app: complex
    spec:
      containers:
        - name: complex-app
          image: 694473223643.dkr.ecr.us-east-1.amazonaws.com/complex-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
